name: Mypy lint and test

# This workflow will run on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  - name: install mypy
    run:
      python -m pip install --upgrade pip
      pip install mypy

  - name: lint
    run:
      mypy .
  
  - name: test
    run:
      python test_runner.py cat
      python test_runner.py hello
      python test_runner.py hello_user_name
      python test_runner.py prob1


