name: Mypy lint and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: lint
        run: |
          mypy op_lib.py rake.py stack_machine.py test_runner.py translator.py
      
      - name: test
        run: |
          python test_runner.py cat
          python test_runner.py hello
          python test_runner.py hello_user_name
          python test_runner.py prob1


